# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# This ensures routing works correctly for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# These headers ensure proper caching and styling consistency
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"